### ISSUE TITLE
Unable to navigate between neovim panes

### ISSUE THREAD

**Issue by ShelpAm** [MunsMan/kitty-navigator.nvim#3]

**Comment by ShelpAm** [comment]
Sorry for my mistake... It works now.

**Comment by jwbackhouse** [comment]
@MunsMan Afraid I'm having the same issue. I have `ctrl-h/l` configured in nvim to move between windows but they're no longer working since I added the same bindings to kitty.conf:

```lua
vim.keymap.set('n', '<C-h>', '<C-w><C-h>', { desc = 'Move focus to the left window' })
vim.keymap.set('n', '<C-l>', '<C-w><C-l>', { desc = 'Move focus to the right window' })
```

So I can move from nvim <-> kitty fine, but not from nvim window 1 <-> window 2

I'm using Lazy with this config:
```
  {
    'MunsMan/kitty-navigator.nvim',
    build = {
      'cp navigate_kitty.py ~/.config/kitty',
      'cp pass_keys.py ~/.config/kitty',
    },
  },
```

Am I missing something?

**Comment by ShelpAm** [comment]
@jwbackhouse Maybe you missed the `key` section. Here is my configuration:
```
return {
  {
    "MunsMan/kitty-navigator.nvim",
    enabled = false,
    build = {
      "cp navigate_kitty.py ~/.config/kitty",
      "cp pass_keys.py ~/.config/kitty",
    },
    keys = {
      { "<C-h>", function() require("kitty-navigator").navigateLeft() end,  desc = "Move left a Split",  mode = { "n" } },
      { "<C-j>", function() require("kitty-navigator").navigateDown() end,  desc = "Move down a Split",  mode = { "n" } },
      { "<C-k>", function() require("kitty-navigator").navigateUp() end,    desc = "Move up a Split",    mode = { "n" } },
      { "<C-l>", function() require("kitty-navigator").navigateRight() end, desc = "Move right a Split", mode = { "n" } },
    },
  }
}
```

**Comment by jwbackhouse** [comment]
Thanks for the quick reply! I was missing those but unfortunately that doesn't fix the issue 😞 

(btw, if it helps then my config is based on [Kickstart](https://github.com/nvim-lua/kickstart.nvim))

**Comment by ShelpAm** [comment]
@jwbackhouse 

The following is in my kitty configuration file, do you have something like this in your configuration?

```
# Key mappings

# Switch focus to the neighboring window in the indicated direction
# map ctrl+h neighboring_window left
# map ctrl+l neighboring_window right
# map ctrl+k neighboring_window up
# map ctrl+j neighboring_window down
# If you are using neovim, enable this to get great experience.
# # nvim integration
# map ctrl+j kitten pass_keys.py neighboring_window bottom ctrl+j
# map ctrl+k kitten pass_keys.py neighboring_window top    ctrl+k
# map ctrl+h kitten pass_keys.py neighboring_window left   ctrl+h
# map ctrl+l kitten pass_keys.py neighboring_window right  ctrl+l
```

**Comment by jwbackhouse** [comment]
Yes, I've got the second block but not the first

**Comment by MunsMan** [comment]
@jwbackhouse did it solve your issue?
How would you upgrade the documentation, so that the setup is easier for new users?

**Comment by jwbackhouse** [comment]
@MunsMan no I'm afraid it didn't - sorry, should have been clearer!

**Comment by ShelpAm** [comment]
I haven't used kitty for a long time. And now I just can't move from neovim to kitty...

Edit: I fixed it. It's because another plugin overrode the config.

**Comment by ShelpAm** [comment]
@jwbackhouse 
To make things clearer, please do the following checks:
- For neovim:
  - [ ] When pressing `<Ctrl-H>`, `require("kitty-navigator").navigateLeft()` is triggered. (Other keys are similar)
- For kitty:
  - [ ] `navigate_kitty.py` and `pass_keys.py` are present in your `~/.config/kitty` dir.
  - [ ] These two options are set:
    ```
      allow_remote_control yes
      listen_on unix:@mykitty
    ```
  - [x] These four lines are in your `kitty.conf` file:
    ```
    map ctrl+j kitten pass_keys.py neighboring_window bottom ctrl+j
    map ctrl+k kitten pass_keys.py neighboring_window top    ctrl+k
    map ctrl+h kitten pass_keys.py neighboring_window left   ctrl+h
    map ctrl+l kitten pass_keys.py neighboring_window right  ctrl+l
    ```

**Comment by ShelpAm** [comment]
I finally figured it out!

There is some bug in the plugin, and I will open a pull-request to fix it.

@jwbackhouse @MunsMan

**Comment by jwbackhouse** [comment]
Amazing, thanks @ShelpAm ! ❤️

**Comment by MunsMan** [comment]
@jwbackhouse Hope the issue is resolved now and the plugin is now working for you.

**Comment by jwbackhouse** [comment]
@MunsMan I'm very sad to say it hasn't helped 😢 . These are all my settings:

nvim/init.lua
```
require('lazy').setup({
{
    'MunsMan/kitty-navigator.nvim',
    build = {
      'cp navigate_kitty.py ~/.config/kitty',
      'cp pass_keys.py ~/.config/kitty',
    },
    opts = { keybindings = {} },
},
...
```

kitty.conf
```
map ctrl+j kitten pass_keys.py neighboring_window bottom ctrl+j
map ctrl+k kitten pass_keys.py neighboring_window top    ctrl+k
map ctrl+h kitten pass_keys.py neighboring_window left   ctrl+h
map ctrl+l kitten pass_keys.py neighboring_window right  ctrl+l
allow_remote_control yes
```

If I remove these kitty.conf settings then I can use ctrl-h/l to change between neovim windows, but then I can't use them to move into the kitty window. If I enable them, I can move into the kitty window but not between neovim windows 🤷🏼 !

I've tried as many combinations as I can think of, including adding the keybindings into `opts` as per your message above, and also adding the additional kitty keybindings from your other message

**Comment by ShelpAm** [comment]
@jwbackhouse Could you please run `:map`, and check what `Ctrl-hjkl` are mapped to? And please don't manually map `Ctrl-hjkl` to any key.

**Comment by jwbackhouse** [comment]
@ShelpAm This is what I get. I notice `hjkl` are in capitals but not sure if that makes a difference?

```
n  <C-K>       * <Lua 37: ~/.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/keys.lua:121>                                                                                                                                      
                 Move up a Split                                                                                                                                                                                                      
n  <C-J>       * <Lua 38: ~/.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/keys.lua:121>                                                                                                                                      
                 Move down a Split                                                                                                                                                                                                    
n  <C-H>       * <Lua 36: ~/.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/keys.lua:121>                                                                                                                                      
                 Move left a Split                                                                                                                                                                                                                                                                                                                                                                                    
n  <C-L>       * <Lua 34: ~/.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/keys.lua:121>                                                                                                                                      
                 Move right a Split  
```

**Comment by ShelpAm** [comment]
@jwbackhouse 

> I notice `hjkl` are in capitals but not sure if that makes a difference?

There isn't much difference.

It seems that the key configuration has been overridden by others; you should remove those lines.

Hint: you could search for text like "Move up a Split" to find them.

**Comment by jwbackhouse** [comment]
@ShelpAm I've unset all of the bindings so that `:map` doesn't list `<C-L>` etc, but no difference. It does mean that even when I remove the Kitty keybindings I can't switch between nvim windows though.
Maybe there's something else I'm missing 🤔 . Feel like I'm taking up too much of your time already!

**Comment by ShelpAm** [comment]
Could you please check if the plugin is up to date and is running when you start neovim?

It's so weird. Normally, the plugin should map C-l to some function.

**Comment by jwbackhouse** [comment]
Sorry for the slow reply. It's definitely running and is on the latest version including your most recent commit. It's a mystery 🤷🏼

**Comment by MunsMan** [comment]
I think in the default kickstarter config, there are default window movements defined

[kickstart](https://github.com/nvim-lua/kickstart.nvim/blob/8d1ef972bc32faa86fee21a57f9033b41f612ebb/init.lua#L188)

If this is not the source of conflict, it might be which a different plugin. 

Do you have your config on GitHub, or somewhere to inspect?

**Comment by jwbackhouse** [comment]
As far as I can see I've disabled those? Here's my [config](https://github.com/jwbackhouse/kickstart.nvim/blob/main/init.lua).

My kitty.conf is as follows:
```
# Copy to clipboard 
map kitty_mod+c copy_to_clipboard
map cmd+c       copy_to_clipboard

#: Paste from clipboard
map kitty_mod+v paste_from_clipboard
map cmd+v       paste_from_clipboard

# Layout change
enabled_layouts tall:bias=80;full_size=1;mirrored=false,splits,stack
# Zoom window
map cmd+m toggle_layout stack
# Create a new window splitting the space used by the existing one so that
# the two windows are placed one above the other
map cmd+d launch --location=hsplit
# the two windows are placed side by side
map cmd+r launch --location=vsplit

map ctrl+shift+left resize_window narrower 10
map ctrl+shift+right resize_window wider 10

# Move the active window in the indicated direction
map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down

map f7 layout_action rotate

# neovim link
map ctrl+j kitten pass_keys.py neighboring_window bottom ctrl+j
map ctrl+k kitten pass_keys.py neighboring_window top    ctrl+k
map ctrl+h kitten pass_keys.py neighboring_window left   ctrl+h
map ctrl+l kitten pass_keys.py neighboring_window right  ctrl+l
allow_remote_control yes
```

If I remove this last block of kitty keybindings, I can use ctrl-l/h to move between windows within nvim - but cannot move from nvim into the adjacent kitty window.
When I add them back, ctrl-h/l allows me to move between nvim and kitty, but not between nvim windows

**Comment by ShelpAm** [comment]
@jwbackhouse
But kitty-navigator.nvim wasn't installed when I tried to switch to your configuration. Where is that?

And from your kitty config, I didn't see a line like `listen_on unix:@mykitty`. You should I it to kitty config.

**Comment by jwbackhouse** [comment]
@ShelpAm Sorry my bad, it's on the `jb-custom` branch - should have checked the link first 🙄 

When I add `listen_on unix:@mykitty` I get an error message on launch: `Invalid listen_on=unix:@mykitty-65746, ignoring`. I'm on MacOS, not Linux btw

**Comment by ShelpAm** [comment]
Using your config, I successfully moved among splits in neovim and kitty. The reason why you can't move is probably that you didn't add `listen_on` to kitty configuration. Despite `listen_on unix:@mykitty` raises error, `listen_on unix:/tmp/mykitty` (for other unix system) deserves a try. I don't know much about this option, though.

Hope that will work.

**Comment by jwbackhouse** [comment]
It's very strange - if I launch kitty from the command line with the following in `<kitty config dir>/macos-launch-services-cmdline` (as per docs [here](https://sw.kovidgoyal.net/kitty/faq/#how-do-i-specify-command-line-options-for-kitty-on-macos)):
```
--listen-on unix:/tmp/mykitty
```

then `<C-L>` works as expected. `<C-H>` allows me to move back from Kitty into nvim, but won't then allow me to move between nvim window 🤯 !

**Comment by MunsMan** [comment]
That sounds like a kitty problem on your side. Kitty is capturing the commands, and might not forward them to Neovim. Try to set up a minimal kitty config and try it again. The last two steps from the README of the plugin are the most imported in this context.

Sadly, I'm not using kitty anymore 😅 therefore, it is challenging to support you there.

**Comment by ShelpAm** [comment]
> Sadly, I'm not using kitty anymore 😅 therefore, it is challenging to support you there.

Nor do I...

**Comment by jwbackhouse** [comment]
Thanks both, appreciate all your help ❤️ . I'll see if I can debug the issue and will post here if i have any success
