### ISSUE TITLE
Conflicting keymaps with fzf/zoxide

### ISSUE THREAD

**Issue by steakhutzeee** [MunsMan/kitty-navigator.nvim#5]
Hi! Thank you very much for the plugin!

I noted that using it I'm unable to use fzf or zoxide keys Ctrl+j/k to move in the results. Is there a way the plugin to be ignored if such a program is running?

Thanks!

**Comment by MunsMan** [comment]
Hello @steakhutzeee,

Thank you for your feedback on the plugin! I'm glad you find it useful.

Regarding your question about `fzf` and `zoxide` key bindings, I understand the desire to maintain compatibility with other tools. However, implementing specific exceptions for individual programs would be challenging to maintain and could potentially lead to conflicts with other plugins or tools.

Instead, I would recommend adjusting the key bindings in either this plugin (`kitty-navigator`) or `fzf`/`zoxide` to resolve the conflict. Most terminal applications and plugins allow for customization of their key bindings. This approach would give you more control and flexibility in setting up your ideal workflow.

Personally, I use `<C-d>` and `<C-u>` for the up and down movements.

Please don't hesitate to reach out if you have any other questions or concerns!

Best regards,
MunsMan
